name: mySearch
channels:
- defaults
dependencies:
- python=3.8
- pip
- pip:
  - requests
  - beautifulsoup4
  - lxml
  - pandas
  - flask
  - pandas
  - readability-lxml
  - lxml_html_clean
  - jieba
  - nltk
  - scikit-learn
  - elasticsearch=8.17.2